### ISSUE TITLE
GOAP not found

### ISSUE THREAD

**Issue by RajShekhorRoy** [kiharalab/DOVE#12]
Hi,

I was running this tool and received an error message "No such file or directory: '/home/rajroy/Downloads/tools/Goap' ". I understand that it did not find the tool named GOAP but I don't know where to get it from to download it.

**Comment by wang3702** [comment]
Please contact the author to get the permission https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3192975/. Then we can release our modified GOAP code to you.
