### ISSUE TITLE
Tensorflow/Keras compatibility problem

### ISSUE THREAD

**Issue by georgkempf** [kiharalab/DOVE#5]
Hello,

I installed tensorflow==0.12 and keras==2.2.4 (keras-2.2.4 keras-applications-1.0.8 keras-preprocessing-1.1.2) as suggested in the Readme but get the following error:
AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'leaky_relu'

Python version is 3.5.6.

I tried a few other tensorflow and keras versions but then other compatibility errors occur.

Best regards.

**Comment by wang3702** [comment]
Thanks a lot for your question! Sorry for the late response!
On our cluster, we used tensorflow 1.10.0 and keras 2.1.5. I think that should work for you.

**Comment by georgkempf** [comment]
Many thanks, with this version combination it worked!

**Comment by wang3702** [comment]
My pleasure.
