### ISSUE TITLE
IndexError: too many indices for array Prepare_Input_Single.py

### ISSUE THREAD

**Issue by jiyanbio** [kiharalab/DOVE#6]
Using TensorFlow backend.
/home/ft_local/ppi_structData/684/bm5_pydock/1JTD/pdb/1JTD_1114_conv888 existed
REMARK            total,bonds,angles,improper,dihe,vdw,elec,noe,cdih,coup,sani,vean,dani

[error] encountered blank atom name
REMARK            bonds,angles,impropers,dihe,noe,cdih,coup,sani,vean,dani

[error] encountered blank atom name
REMARK               noe,cdih,coup,sani,vean,dani

[error] encountered blank atom name
REMARK               >0.3,>5,>1,>0,>5,>0.2

[error] encountered blank atom name
REMARK                        CVpartition#,violations,rms

[error] encountered blank atom name
END

[error] encountered blank atom name
waiting dealing1
in total, we have 486 residues in receptor, 0 residues in ligand
in the interface 10A cut off, we have 0 residue, 0 atoms in the receptor
in the interface 10A cut off, we have 0 residue, 0 atoms in the ligand
Traceback (most recent call last):
  File "main.py", line 67, in <module>
    record,input_path=run_pred_single(file_path,random_id,gpu_id)
  File "main.py", line 16, in run_pred_single
    input_path=Prepare_Input_Singe(file_path,random_id)
  File "/home/ft_local/PycharmProjects/DOVE/Input_Preparing/Prepare_Input_Single.py", line 45, in Prepare_Input_Singe
    tempload, rlength, llength = reform_input(rlist, llist, 1)
  File "/home/ft_local/PycharmProjects/DOVE/data_processing/prepare_input.py", line 286, in reform_input
    xmean=np.mean(coordinate[:,0])
IndexError: too many indices for array
Using TensorFlow backend.

**Comment by jiyanbio** [comment]
pdb file location: https://www.dropbox.com/s/tpyguaa2mgxng0w/1JTD_1114_conv.pdb?dl=0

**Comment by wang3702** [comment]
Sorry for the late response. I think the error comes from the receptor and ligand recognition. To fix this bug, personally I think you should change your pdb format. Please first put receptor with chain "A" in pdb, then put the ligand with chain "B" in pdb.
